### ISSUE TITLE
`makeOutFile` does not check whether the file is already opened

### ISSUE THREAD

**Issue by maxfl** [mjkramer/SelectorFramework#2]
If `makeOutFile` is called the second time with the same label, new file will be created, while the old file will be lost: not closed and not deleted.

There is no issue if a single output file is expected. If the output file will be changed during the analysis the data will be lost.

**Comment by maxfl** [comment]
Solved in f538f74.

**Comment by maxfl** [comment]
@mjkramer

**Comment by mjkramer** [comment]
Applied in https://github.com/mjkramer/SelectorFramework/commit/fc5150a7ad294d22d066141c8ea66b9b7179cbfa
