### ISSUE TITLE
Output file is closed before the tree is written

### ISSUE THREAD

**Issue by maxfl** [mjkramer/SelectorFramework#3]
The `~Pipeline` is called before the `~MuonSaver`. Obviously all the objects, owned by `Pipeline` should be available during destruction. `~Pipeline` closes the output file and `~MuonSaver` is unable to save the data.

**Comment by maxfl** [comment]
@mjkramer

**Comment by maxfl** [comment]
Fixed in maxfl/IbdSel@27c59cc and a8504b5

**Comment by mjkramer** [comment]
Thanks, good catch. Alternative fix was applied in https://github.com/mjkramer/SelectorFramework/commit/0a20ce3e1039f93d42bb3e09c382ebb913d33c03, no need to have/call TreeWriter::write in this case.
